apiVersion: v1
kind: ConfigMap
metadata:
  name: jyotish-config
  namespace: jyotish
data:
  NODE_ENV: "dev"
  PORT: "5000"
  DB_HOST: "jyotish-mysql"
  DB_PORT: "3306"
  DB_NAME: "jyotish_db"
  DB_USER: "root"
