apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jyotish-ingress
  namespace: jyotish
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: jyotish-backend
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jyotish-frontend
                port:
                  number: 80