apiVersion: v1
kind: Secret
metadata:
  name: jyotish-secrets
  namespace: jyotish
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "123456"
  MYSQL_DATABASE: "jyotish_db"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "123456"
  GEMINI_API_KEY: "your-google-gemini-key"
